spring.application.name=app

# MySql configurations
spring.datasource.url=jdbc:mysql://localhost:3306/booking_train?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Java Persistence API) configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# H2 configurations
#spring.datasource.url=jdbc:h2:file:./data/demo;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

# Thymeleaf configurations
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/

#Mail configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chrisnguyeen2000@gmail.com
spring.mail.password=anrvxhcwldwoyszc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=chrisnguyeen2000@gmail.com

# Allow Override Bean
spring.main.allow-bean-definition-overriding=true

# Handle custom Exception
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/**


# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
openapi.service.title=Train Ticket Booking Client API
openapi.service.version=v1.0.0
openapi.service.server=http://localhost:8080
openapi.service.description=This API for client user.

# Github OAuth2
#spring.security.oauth2.client.registration.github.client-id=
#spring.security.oauth2.client.registration.github.client-secret=
#spring.security.oauth2.client.registration.github.scope=read:user,user:email
#spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
#
#spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
#spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
#spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
#spring.security.oauth2.client.provider.github.user-name-attribute=id
#
## Google
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
#spring.security.oauth2.client.registration.google.scope=profile,email
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
#
#spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
#spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
#spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

frontend.url=http://localhost:3000
jwt.secret=84e68f81bf7e7a317287e7614046d979f4bb172ecdcd553747b3e21204f6fb0e1f7edff241ced32e12bb26ec3ab17b982c4aee1cab2c915423f776a66d41411790c3f7f3d4aaa5dbea7843c28438b28ffb32e8065de319adfc0811dd2300154d12acb027fd81191c0bf613f7ebcfcb59723d0b288b1783bca3d615c278ac10b1d7534c9a5405592cc25b85f4835a8e71a4fc54604b56cfab7fcb3fe3e7d32a044942da6ae824c8e9e992c3636b159b2ddecf17b0da91385b6036ef899a0a47b91df2c47def498b980cd9348c7b8a48c31e7505a5cc0a975dde0604647c67c20f9c9a3973c152bc4c5ebbe6af2d30083c361889f415327975c0ea010ace62b434
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
upload.dir=src/main/resources/static/images/profiles/

server.servlet.session.timeout=24h


spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.timeout=2000ms